from modules.proto.embedding.embedding_buffer_pb2_grpc import EmbeddingServiceServicer, add_EmbeddingServiceServicer_to_server, EmbeddingServiceStub
from modules.proto.embedding.embedding_buffer_pb2 import EmbeddingRequest, EmbeddingResponse
